/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package alpari;

import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;

/**
 *
 * @author Dell E6540
 */
public class alp extends javax.swing.JFrame {
int second=0;

    public alp() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        header = new javax.swing.JLabel();
        detail_holder = new javax.swing.JPanel();
        upp_details = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        hours = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        minutes = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        seconds1 = new javax.swing.JLabel();
        down_details = new javax.swing.JPanel();
        seconds2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setLayout(null);

        header.setBackground(new java.awt.Color(255, 255, 255));
        header.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        header.setForeground(new java.awt.Color(204, 204, 204));
        header.setText(" one hour TF");
        jPanel1.add(header);
        header.setBounds(320, 20, 390, 50);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 10, 850, 80);

        detail_holder.setLayout(null);

        upp_details.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.setLayout(null);

        hours.setBackground(new java.awt.Color(204, 204, 204));
        hours.setFont(new java.awt.Font("Tahoma", 1, 70)); // NOI18N
        hours.setForeground(new java.awt.Color(204, 204, 204));
        hours.setText("00");
        jPanel2.add(hours);
        hours.setBounds(50, 30, 100, 100);

        upp_details.add(jPanel2);
        jPanel2.setBounds(30, 0, 190, 170);

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));
        jPanel3.setLayout(null);

        minutes.setBackground(new java.awt.Color(204, 204, 204));
        minutes.setFont(new java.awt.Font("Tahoma", 1, 70)); // NOI18N
        minutes.setForeground(new java.awt.Color(204, 204, 204));
        minutes.setText("00");
        jPanel3.add(minutes);
        minutes.setBounds(50, 30, 100, 100);

        upp_details.add(jPanel3);
        jPanel3.setBounds(330, 0, 190, 170);

        jPanel4.setBackground(new java.awt.Color(102, 102, 102));
        jPanel4.setLayout(null);

        seconds1.setBackground(new java.awt.Color(204, 204, 204));
        seconds1.setFont(new java.awt.Font("Tahoma", 1, 70)); // NOI18N
        seconds1.setForeground(new java.awt.Color(204, 204, 204));
        seconds1.setText("00");
        jPanel4.add(seconds1);
        seconds1.setBounds(50, 30, 100, 100);

        upp_details.add(jPanel4);
        jPanel4.setBounds(600, 0, 190, 170);

        detail_holder.add(upp_details);
        upp_details.setBounds(0, 0, 840, 170);

        down_details.setLayout(null);

        seconds2.setBackground(new java.awt.Color(204, 204, 204));
        seconds2.setFont(new java.awt.Font("Tahoma", 1, 70)); // NOI18N
        seconds2.setForeground(new java.awt.Color(204, 204, 204));
        seconds2.setText("00");
        down_details.add(seconds2);
        seconds2.setBounds(370, 50, 100, 100);

        detail_holder.add(down_details);
        down_details.setBounds(0, 230, 840, 200);

        getContentPane().add(detail_holder);
        detail_holder.setBounds(20, 110, 840, 430);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
       
       
    }//GEN-LAST:event_formWindowActivated

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
         // to start the function when the program starts
         fun();
        
    }//GEN-LAST:event_formWindowOpened

    
    public static void main(String args[]) {
        
    
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new alp().setVisible(true);
            }
        });
        
       
        
       
    }
    public  void delayForASec() 
   { 
        try {
            Thread.sleep(1000);
        } catch (InterruptedException ex) {
            Logger.getLogger(alp.class.getName()).log(Level.SEVERE, null, ex);
        }
       
   }
    public  void fun()
    {
        
        for (int i =1;i<61;i++)
        {
            
            delayForASec();
            second=i;
            
           seconds2.setText(String.valueOf(i));
            
            System.out.println(i+" sec");
        
        }
        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel detail_holder;
    private javax.swing.JPanel down_details;
    private javax.swing.JLabel header;
    private javax.swing.JLabel hours;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel minutes;
    private javax.swing.JLabel seconds1;
    private javax.swing.JLabel seconds2;
    private javax.swing.JPanel upp_details;
    // End of variables declaration//GEN-END:variables
}
